service: node-aws-test

provider:
  name: aws
  stage: development
  runtime: nodejs12.x
  timeout: 10
  memory: 128


functions:
  helloWorld:
    handler: index.helloWorld
    description: Hello world function
    environment:
      ENV: development
    events:
      - http:
          path: /{name}
          method: GET
          cors: true
  sum:
    handler: index.sum
    description: Sum function
    events:
      - http:
          path: /suma
          method: POST
          cors: true
          private: true

plugins:
  - serverless-offline